# Generated by Django 4.2.3 on 2023-07-26 04:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('posted_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_types', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_description', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('company_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('company_website', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_per_hour', models.CharField(blank=True, max_length=1000, null=True)),
                ('salary', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('apply_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
