# Generated by Django 4.2.3 on 2023-07-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetail',
            old_name='apply_link',
            new_name='company_country',
        ),
        migrations.RenameField(
            model_name='jobdetail',
            old_name='job_types',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='jobdetail',
            old_name='location',
            new_name='company_info',
        ),
        migrations.RenameField(
            model_name='jobdetail',
            old_name='posted_date',
            new_name='company_location',
        ),
        migrations.RenameField(
            model_name='jobdetail',
            old_name='job_description',
            new_name='job_description_format',
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='company_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='company_logo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='company_size',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='company_slogan',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='company_state',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='company_zip_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='is_approved',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='is_featured',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='is_filled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='is_public',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='job_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='job_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='job_country',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='job_created_at',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='job_expires_at',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='job_state',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='job_zip_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='payment_method',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='remote_ready',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='wpjobboard_am_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
