# Generated by Django 4.2.3 on 2023-07-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_apply_link_jobdetail_company_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='update_at',
        ),
    ]
