# Generated by Django 4.2.3 on 2023-07-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_jobdetail_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetail',
            old_name='job_description_format',
            new_name='job_description',
        ),
    ]
